spring.datasource.url=jdbc:postgresql://dpg-d6rhlr75gffc73f9t270-a.oregon-postgres.render.com:5432/odisehabits
spring.datasource.username=odisepostgres
spring.datasource.password=2JZmMj2oStgGWFlwU2lUAOlM8c4VV2aL

jwt.secret=mi_clave_super_segura_de_al_menos_32_caracteres_123

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true